services:
  # prometheus:
  #   image: docker.arvancloud.ir/prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  #     - prometheus-data:/prometheus
  #   networks:
  #     - localprom
  #   ports:
  #     - 9090:9090
  # node-exporter:
  #   image: docker.arvancloud.ir/prom/node-exporter
  #   container_name: node_exporter
  #   networks:
  #     - localprom
  #   ports:
  #     - 9100:9100
  # grafana:
  #   image: docker.arvancloud.ir/grafana/grafana:latest
  #   container_name: grafana
  #   networks:
  #     - localprom
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #     - /etc/grafana/grafana.ini:/etc/grafana/grafana.ini
  kafka-producer:
    build: producer/.
    container_name: kafka-producer
    networks: 
      - localprom
    depends_on:
      - kafka
  kafka-consumer:
    build: consumer/.
    container_name: kafka-consumer
    networks: 
      - localprom
    depends_on:
      - kafka
      - kafka-producer
  zookeeper:
    image: docker.arvancloud.ir/bitnami/zookeeper:latest
    container_name: zookeeper
    ports: 
      - 2181:2181
    networks: 
      - localprom
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka:
  #   image: docker.arvancloud.ir/apache/kafka:latest
  #   container_name: kafka
  #   networks: 
  #     - localprom
  #   ports: 
  #     - 9092:9092
  kafka:
    image: docker.arvancloud.ir/bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - localprom
    environment:
      - KAFKA_LISTENERS=EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
networks:
  localprom:
    driver: bridge

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local